name: microsoft_graph_api
description: Flutter package for seamless Microsoft 365 data access via Microsoft Graph API.
version: 0.0.9
repository: https://github.com/PlaxXOnline/microsoft_graph_api
issue_tracker: https://github.com/PlaxXOnline/microsoft_graph_api/issues

platforms:
  android:
  ios:
  windows:
  linux:
  macos:
  web:

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  dio: ^5.2.1+1
  mockito: ^5.4.2
  json_annotation: ^4.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  assets:
    - assets/user-shadow.png
